version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: applications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "5000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: